export const TOGGLE_IS_MODAL = 'TOGGLE_IS_MODAL';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const TOGGLE_IS_CHECK_ADDED = 'TOGGLE_IS_CHECK_ADDED';
export const ADD_CURRENT_CHECK = 'ADD_CURRENT_CHECK';
export const TOGGLE_IS_MODAL_INPUT = 'TOGGLE_IS_MODAL_INPUT';
export const TOGGLE_IS_SCANNER = 'TOGGLE_IS_SCANNER';